[2025-08-20T17:58:25.068+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-20T17:58:25.100+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline_dvc.train_fraud_detector_dvc manual__2025-08-20T17:57:10.749381+00:00 [queued]>
[2025-08-20T17:58:25.112+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline_dvc.train_fraud_detector_dvc manual__2025-08-20T17:57:10.749381+00:00 [queued]>
[2025-08-20T17:58:25.113+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-20T17:58:25.129+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): train_fraud_detector_dvc> on 2025-08-20 17:57:10.749381+00:00
[2025-08-20T17:58:25.141+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1743) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-20T17:58:25.143+0000] {standard_task_runner.py:63} INFO - Started process 1769 to run task
[2025-08-20T17:58:25.143+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline_dvc', 'train_fraud_detector_dvc', 'manual__2025-08-20T17:57:10.749381+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline_dvc_dag.py', '--cfg-path', '/tmp/tmp3p55m23t']
[2025-08-20T17:58:25.147+0000] {standard_task_runner.py:91} INFO - Job 12: Subtask train_fraud_detector_dvc
[2025-08-20T17:58:25.330+0000] {task_command.py:426} INFO - Running <TaskInstance: ml_pipeline_dvc.train_fraud_detector_dvc manual__2025-08-20T17:57:10.749381+00:00 [running]> on host d741d36e6db0
[2025-08-20T17:58:25.457+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='yas' AIRFLOW_CTX_DAG_ID='ml_pipeline_dvc' AIRFLOW_CTX_TASK_ID='train_fraud_detector_dvc' AIRFLOW_CTX_EXECUTION_DATE='2025-08-20T17:57:10.749381+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-20T17:57:10.749381+00:00'
[2025-08-20T17:58:25.458+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-20T17:58:25.489+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-20T17:58:25.491+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n            git config --global --add safe.directory /opt/***/ml_pipeline\n            cd /opt/***/ml_pipeline\n            dvc pull --force\n            dvc repro train_model\n            dvc push\n        ']
[2025-08-20T17:58:25.511+0000] {subprocess.py:86} INFO - Output:
[2025-08-20T17:58:29.197+0000] {subprocess.py:93} INFO - A       data/raw/
[2025-08-20T17:58:29.201+0000] {subprocess.py:93} INFO - 1 file added
[2025-08-20T17:58:35.309+0000] {subprocess.py:93} INFO - Running stage 'ingest':
[2025-08-20T17:58:35.311+0000] {subprocess.py:93} INFO - > python data/ingest/etl_task.py && python data/ingest/download_data.py
[2025-08-20T17:58:38.377+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-20T17:58:38.379+0000] {subprocess.py:93} INFO -   File "/opt/***/ml_pipeline/data/ingest/etl_task.py", line 10, in <module>
[2025-08-20T17:58:38.381+0000] {subprocess.py:93} INFO -     logger = get_logger("model_training", tracing=False)
[2025-08-20T17:58:38.382+0000] {subprocess.py:93} INFO -              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-20T17:58:38.383+0000] {subprocess.py:93} INFO - TypeError: get_logger() got an unexpected keyword argument 'tracing'
[2025-08-20T17:58:38.668+0000] {subprocess.py:93} INFO - ERROR: failed to reproduce 'ingest': failed to run: python data/ingest/etl_task.py && python data/ingest/download_data.py, exited with 1
[2025-08-20T17:58:43.692+0000] {subprocess.py:93} INFO - Everything is up to date.
[2025-08-20T17:58:44.244+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-08-20T17:58:44.246+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-20T17:58:44.291+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ml_pipeline_dvc, task_id=train_fraud_detector_dvc, run_id=manual__2025-08-20T17:57:10.749381+00:00, execution_date=20250820T175710, start_date=20250820T175825, end_date=20250820T175844
[2025-08-20T17:58:44.327+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-20T17:58:44.351+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-20T17:58:44.355+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
