[2025-08-17T18:36:01.948+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-17T18:36:01.979+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline_dvc.preprocess_dvc manual__2025-08-17T18:35:45.412026+00:00 [queued]>
[2025-08-17T18:36:01.988+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline_dvc.preprocess_dvc manual__2025-08-17T18:35:45.412026+00:00 [queued]>
[2025-08-17T18:36:01.989+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-17T18:36:02.006+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): preprocess_dvc> on 2025-08-17 18:35:45.412026+00:00
[2025-08-17T18:36:02.013+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2108) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-17T18:36:02.015+0000] {standard_task_runner.py:63} INFO - Started process 2125 to run task
[2025-08-17T18:36:02.015+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline_dvc', 'preprocess_dvc', 'manual__2025-08-17T18:35:45.412026+00:00', '--job-id', '309', '--raw', '--subdir', 'DAGS_FOLDER/train_pipeline_dag.py', '--cfg-path', '/tmp/tmp01rbz_qb']
[2025-08-17T18:36:02.017+0000] {standard_task_runner.py:91} INFO - Job 309: Subtask preprocess_dvc
[2025-08-17T18:36:02.075+0000] {task_command.py:426} INFO - Running <TaskInstance: ml_pipeline_dvc.preprocess_dvc manual__2025-08-17T18:35:45.412026+00:00 [running]> on host bea494a05fb4
[2025-08-17T18:36:02.198+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='yas' AIRFLOW_CTX_DAG_ID='ml_pipeline_dvc' AIRFLOW_CTX_TASK_ID='preprocess_dvc' AIRFLOW_CTX_EXECUTION_DATE='2025-08-17T18:35:45.412026+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-17T18:35:45.412026+00:00'
[2025-08-17T18:36:02.199+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-17T18:36:02.215+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-17T18:36:02.216+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n            cd /opt/***/ml_pipeline\n            dvc pull\n            dvc repro preprocess\n            dvc push\n        ']
[2025-08-17T18:36:02.228+0000] {subprocess.py:86} INFO - Output:
[2025-08-17T18:36:05.185+0000] {subprocess.py:93} INFO - ERROR: failed to pull data from the cloud - Can't remove the following unsaved files without confirmation. Use `--force` to force.
[2025-08-17T18:36:05.186+0000] {subprocess.py:93} INFO - /opt/***/ml_pipeline/artifacts/models/fraud/metadata_model_v20250817_175136.json
[2025-08-17T18:36:08.585+0000] {subprocess.py:93} INFO - Stage 'ingest' didn't change, skipping
[2025-08-17T18:36:08.620+0000] {subprocess.py:93} INFO - Stage 'preprocess' didn't change, skipping
[2025-08-17T18:36:08.625+0000] {subprocess.py:93} INFO - Data and pipelines are up to date.
[2025-08-17T18:36:12.594+0000] {subprocess.py:93} INFO - Everything is up to date.
[2025-08-17T18:36:13.040+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-08-17T18:36:13.042+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-17T18:36:13.090+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ml_pipeline_dvc, task_id=preprocess_dvc, run_id=manual__2025-08-17T18:35:45.412026+00:00, execution_date=20250817T183545, start_date=20250817T183601, end_date=20250817T183613
[2025-08-17T18:36:13.154+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-17T18:36:13.213+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-17T18:36:13.216+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
