[2025-08-15T00:56:04.809+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-15T00:56:04.927+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline_dvc.preprocess_dvc manual__2025-08-15T00:56:01.323876+00:00 [queued]>
[2025-08-15T00:56:04.961+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline_dvc.preprocess_dvc manual__2025-08-15T00:56:01.323876+00:00 [queued]>
[2025-08-15T00:56:04.963+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-15T00:56:05.010+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): preprocess_dvc> on 2025-08-15 00:56:01.323876+00:00
[2025-08-15T00:56:05.029+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=666) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-15T00:56:05.033+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline_dvc', 'preprocess_dvc', 'manual__2025-08-15T00:56:01.323876+00:00', '--job-id', '224', '--raw', '--subdir', 'DAGS_FOLDER/train_pipeline_dag.py', '--cfg-path', '/tmp/tmpot0g2qfe']
[2025-08-15T00:56:05.039+0000] {standard_task_runner.py:63} INFO - Started process 667 to run task
[2025-08-15T00:56:05.041+0000] {standard_task_runner.py:91} INFO - Job 224: Subtask preprocess_dvc
[2025-08-15T00:56:05.154+0000] {task_command.py:426} INFO - Running <TaskInstance: ml_pipeline_dvc.preprocess_dvc manual__2025-08-15T00:56:01.323876+00:00 [running]> on host 97971cf4e9e1
[2025-08-15T00:56:05.374+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='yas' AIRFLOW_CTX_DAG_ID='ml_pipeline_dvc' AIRFLOW_CTX_TASK_ID='preprocess_dvc' AIRFLOW_CTX_EXECUTION_DATE='2025-08-15T00:56:01.323876+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-15T00:56:01.323876+00:00'
[2025-08-15T00:56:05.377+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-15T00:56:05.435+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-15T00:56:05.446+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        cd /opt/***/ml_pipeline\n        dvc pull data/raw.dvc \n        dvc repro preprocess\n        dvc push\n        ']
[2025-08-15T00:56:05.488+0000] {subprocess.py:86} INFO - Output:
[2025-08-15T00:56:10.506+0000] {subprocess.py:93} INFO - Everything is up to date.
[2025-08-15T00:56:15.383+0000] {subprocess.py:93} INFO - 'data/raw.dvc' didn't change, skipping
[2025-08-15T00:56:15.414+0000] {subprocess.py:93} INFO - 'version_meta.json.dvc' didn't change, skipping
[2025-08-15T00:56:15.484+0000] {subprocess.py:93} INFO - Running stage 'preprocess':
[2025-08-15T00:56:15.485+0000] {subprocess.py:93} INFO - > python preprocessing/preprocess_task.py
[2025-08-15T00:56:18.036+0000] {subprocess.py:93} INFO - {"asctime": "2025-08-15 00:56:17,926", "levelname": "INFO", "name": "preprocessing_pipeline", "trace_id": null, "span_id": null, "message": "version_meta.json loaded from local path!"}
[2025-08-15T00:56:18.079+0000] {subprocess.py:93} INFO - {"asctime": "2025-08-15 00:56:18,078", "levelname": "INFO", "name": "preprocessing_pipeline", "trace_id": null, "span_id": null, "message": "preprocessor trained!"}
[2025-08-15T00:56:18.085+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-15T00:56:18.086+0000] {subprocess.py:93} INFO -   File "/opt/***/ml_pipeline/preprocessing/preprocess_task.py", line 54, in <module>
[2025-08-15T00:56:18.086+0000] {subprocess.py:93} INFO -     os.mkdir("data/processed", exists=ok, parents=True)
[2025-08-15T00:56:18.087+0000] {subprocess.py:93} INFO -                                       ^^
[2025-08-15T00:56:18.087+0000] {subprocess.py:93} INFO - NameError: name 'ok' is not defined. Did you mean: 'os'?
[2025-08-15T00:56:18.361+0000] {subprocess.py:93} INFO - ERROR: failed to reproduce 'preprocess': failed to run: python preprocessing/preprocess_task.py, exited with 1
[2025-08-15T00:56:20.938+0000] {subprocess.py:93} INFO - Everything is up to date.
[2025-08-15T00:56:21.196+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-08-15T00:56:21.198+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-15T00:56:21.239+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ml_pipeline_dvc, task_id=preprocess_dvc, run_id=manual__2025-08-15T00:56:01.323876+00:00, execution_date=20250815T005601, start_date=20250815T005604, end_date=20250815T005621
[2025-08-15T00:56:21.301+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-15T00:56:21.321+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-15T00:56:21.324+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
