[2025-08-12T21:52:08.113+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-12T21:52:08.146+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline_dvc.train_outlier manual__2025-08-12T21:51:51.495065+00:00 [queued]>
[2025-08-12T21:52:08.160+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline_dvc.train_outlier manual__2025-08-12T21:51:51.495065+00:00 [queued]>
[2025-08-12T21:52:08.161+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-12T21:52:08.189+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): train_outlier> on 2025-08-12 21:51:51.495065+00:00
[2025-08-12T21:52:08.197+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1009) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-12T21:52:08.200+0000] {standard_task_runner.py:63} INFO - Started process 1027 to run task
[2025-08-12T21:52:08.200+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline_dvc', 'train_outlier', 'manual__2025-08-12T21:51:51.495065+00:00', '--job-id', '192', '--raw', '--subdir', 'DAGS_FOLDER/train_pipeline_dag.py', '--cfg-path', '/tmp/tmp9y2ykjmi']
[2025-08-12T21:52:08.202+0000] {standard_task_runner.py:91} INFO - Job 192: Subtask train_outlier
[2025-08-12T21:52:08.267+0000] {task_command.py:426} INFO - Running <TaskInstance: ml_pipeline_dvc.train_outlier manual__2025-08-12T21:51:51.495065+00:00 [running]> on host ae67cab33f2f
[2025-08-12T21:52:08.408+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='yas' AIRFLOW_CTX_DAG_ID='ml_pipeline_dvc' AIRFLOW_CTX_TASK_ID='train_outlier' AIRFLOW_CTX_EXECUTION_DATE='2025-08-12T21:51:51.495065+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-12T21:51:51.495065+00:00'
[2025-08-12T21:52:08.412+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-12T21:52:08.434+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-12T21:52:08.436+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/ml_pipeline && dvc repro train_outlier']
[2025-08-12T21:52:08.452+0000] {subprocess.py:86} INFO - Output:
[2025-08-12T21:52:12.705+0000] {subprocess.py:93} INFO - ERROR: Unable to acquire lock. Most likely another DVC process is running or was terminated abruptly. Check the page <https://dvc.org/doc/user-guide/troubleshooting#lock-issue> for other possible reasons and to learn how to resolve this.
[2025-08-12T21:52:12.967+0000] {subprocess.py:97} INFO - Command exited with return code 255
[2025-08-12T21:52:12.968+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-12T21:52:12.985+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 255.
[2025-08-12T21:52:12.991+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=ml_pipeline_dvc, task_id=train_outlier, run_id=manual__2025-08-12T21:51:51.495065+00:00, execution_date=20250812T215151, start_date=20250812T215208, end_date=20250812T215212
[2025-08-12T21:52:13.033+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 192 for task train_outlier (Bash command failed. The command returned a non-zero exit code 255.; 1027)
[2025-08-12T21:52:13.056+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-12T21:52:13.086+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-12T21:52:13.088+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
