[2025-08-05T19:35:12.472+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-05T19:35:12.575+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline_dvc.train_dvc manual__2025-08-05T19:34:49.832010+00:00 [queued]>
[2025-08-05T19:35:12.602+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline_dvc.train_dvc manual__2025-08-05T19:34:49.832010+00:00 [queued]>
[2025-08-05T19:35:12.604+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-05T19:35:12.655+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): train_dvc> on 2025-08-05 19:34:49.832010+00:00
[2025-08-05T19:35:12.673+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1332) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-05T19:35:12.680+0000] {standard_task_runner.py:63} INFO - Started process 1333 to run task
[2025-08-05T19:35:12.679+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline_dvc', 'train_dvc', 'manual__2025-08-05T19:34:49.832010+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline_dag_2.py', '--cfg-path', '/tmp/tmp3123bovj']
[2025-08-05T19:35:12.683+0000] {standard_task_runner.py:91} INFO - Job 21: Subtask train_dvc
[2025-08-05T19:35:12.828+0000] {task_command.py:426} INFO - Running <TaskInstance: ml_pipeline_dvc.train_dvc manual__2025-08-05T19:34:49.832010+00:00 [running]> on host cb274dbeb17b
[2025-08-05T19:35:13.083+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='yas' AIRFLOW_CTX_DAG_ID='ml_pipeline_dvc' AIRFLOW_CTX_TASK_ID='train_dvc' AIRFLOW_CTX_EXECUTION_DATE='2025-08-05T19:34:49.832010+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-05T19:34:49.832010+00:00'
[2025-08-05T19:35:13.087+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-05T19:35:13.158+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-05T19:35:13.161+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/ml_pipeline && dvc repro train']
[2025-08-05T19:35:13.196+0000] {subprocess.py:86} INFO - Output:
[2025-08-05T19:35:16.873+0000] {subprocess.py:93} INFO - Stage 'preprocess' didn't change, skipping
[2025-08-05T19:35:17.109+0000] {subprocess.py:93} INFO - Running stage 'train':
[2025-08-05T19:35:17.110+0000] {subprocess.py:93} INFO - > python train/train_task.py
[2025-08-05T19:35:22.989+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-05T19:35:22.990+0000] {subprocess.py:93} INFO -   File "/opt/***/ml_pipeline/train/train_task.py", line 155, in <module>
[2025-08-05T19:35:22.991+0000] {subprocess.py:93} INFO -     main()
[2025-08-05T19:35:22.992+0000] {subprocess.py:93} INFO -   File "/opt/***/ml_pipeline/train/train_task.py", line 142, in main
[2025-08-05T19:35:22.994+0000] {subprocess.py:93} INFO -     outlier_file = train_outlier_detector(X_transformed)
[2025-08-05T19:35:22.995+0000] {subprocess.py:93} INFO -                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-05T19:35:22.996+0000] {subprocess.py:93} INFO -   File "/opt/***/ml_pipeline/train/train_task.py", line 48, in train_outlier_detector
[2025-08-05T19:35:22.997+0000] {subprocess.py:93} INFO -     outlier_file = outlier_detector(X_transformed)
[2025-08-05T19:35:22.998+0000] {subprocess.py:93} INFO -                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-05T19:35:22.999+0000] {subprocess.py:93} INFO - TypeError: 'module' object is not callable
[2025-08-05T19:35:23.465+0000] {subprocess.py:93} INFO - ERROR: failed to reproduce 'train': failed to run: python train/train_task.py, exited with 1
[2025-08-05T19:35:23.876+0000] {subprocess.py:97} INFO - Command exited with return code 255
[2025-08-05T19:35:23.878+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-05T19:35:23.897+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 255.
[2025-08-05T19:35:23.911+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=ml_pipeline_dvc, task_id=train_dvc, run_id=manual__2025-08-05T19:34:49.832010+00:00, execution_date=20250805T193449, start_date=20250805T193512, end_date=20250805T193523
[2025-08-05T19:35:23.936+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 21 for task train_dvc (Bash command failed. The command returned a non-zero exit code 255.; 1333)
[2025-08-05T19:35:23.983+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-05T19:35:24.011+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-05T19:35:24.013+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
