[2025-08-06T03:33:00.399+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-06T03:33:00.436+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline_dvc.train_dvc manual__2025-08-06T03:27:26.716603+00:00 [queued]>
[2025-08-06T03:33:00.447+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline_dvc.train_dvc manual__2025-08-06T03:27:26.716603+00:00 [queued]>
[2025-08-06T03:33:00.448+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-08-06T03:33:00.465+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): train_dvc> on 2025-08-06 03:27:26.716603+00:00
[2025-08-06T03:33:00.475+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=385) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-06T03:33:00.478+0000] {standard_task_runner.py:63} INFO - Started process 386 to run task
[2025-08-06T03:33:00.478+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline_dvc', 'train_dvc', 'manual__2025-08-06T03:27:26.716603+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline_dag_2.py', '--cfg-path', '/tmp/tmpkq1fixnu']
[2025-08-06T03:33:00.480+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask train_dvc
[2025-08-06T03:33:00.551+0000] {task_command.py:426} INFO - Running <TaskInstance: ml_pipeline_dvc.train_dvc manual__2025-08-06T03:27:26.716603+00:00 [running]> on host 1d9cc99197c4
[2025-08-06T03:33:00.700+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='yas' AIRFLOW_CTX_DAG_ID='ml_pipeline_dvc' AIRFLOW_CTX_TASK_ID='train_dvc' AIRFLOW_CTX_EXECUTION_DATE='2025-08-06T03:27:26.716603+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-06T03:27:26.716603+00:00'
[2025-08-06T03:33:00.704+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-06T03:33:00.727+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-06T03:33:00.729+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/ml_pipeline && dvc repro train']
[2025-08-06T03:33:00.744+0000] {subprocess.py:86} INFO - Output:
[2025-08-06T03:33:03.423+0000] {subprocess.py:93} INFO - Running stage 'preprocess':
[2025-08-06T03:33:03.424+0000] {subprocess.py:93} INFO - > python preprocessing/preprocess_task.py
[2025-08-06T03:33:05.791+0000] {subprocess.py:93} INFO - {"asctime": "2025-08-06 03:33:05,791", "levelname": "INFO", "message": "\u2705 Saved pipeline: artifacts/preprocess/pipeline_v20250801_144307.pkl"}
[2025-08-06T03:33:05.795+0000] {subprocess.py:93} INFO - {"asctime": "2025-08-06 03:33:05,791", "levelname": "INFO", "message": "\ud83d\udcc4 Saved metadata: artifacts/preprocess/preprocess_metadata_v20250801_144307.json"}
[2025-08-06T03:33:05.797+0000] {subprocess.py:93} INFO - {"asctime": "2025-08-06 03:33:05,791", "levelname": "INFO", "message": "\ud83d\udce6 Updated version_meta.json"}
[2025-08-06T03:33:06.165+0000] {subprocess.py:93} INFO - Updating lock file 'dvc.lock'
[2025-08-06T03:33:06.182+0000] {subprocess.py:93} INFO - 
[2025-08-06T03:33:06.293+0000] {subprocess.py:93} INFO - Running stage 'train':
[2025-08-06T03:33:06.294+0000] {subprocess.py:93} INFO - > python train/train_task.py
[2025-08-06T03:33:11.286+0000] {subprocess.py:93} INFO - INFO:__main__:Outlier detector saved to artifacts/models/outlier_detector_v20250801_144307.pkl
[2025-08-06T03:33:11.311+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:1201: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
[2025-08-06T03:33:11.323+0000] {subprocess.py:93} INFO -   warnings.warn(
[2025-08-06T03:33:11.339+0000] {subprocess.py:93} INFO - INFO:__main__:üìÑ Training metadata saved to artifacts/train/train_metadata_v20250801_144307.json
[2025-08-06T03:33:11.340+0000] {subprocess.py:93} INFO - INFO:__main__:üì¶ Updated version_meta.json
[2025-08-06T03:33:11.341+0000] {subprocess.py:93} INFO - INFO:__main__:üìÑ Registering the model FraudDetectionModel
[2025-08-06T03:33:11.659+0000] {subprocess.py:93} INFO - 2025/08/06 03:33:11 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
[2025-08-06T03:33:11.660+0000] {subprocess.py:93} INFO - The git executable must be specified in one of the following ways:
[2025-08-06T03:33:11.661+0000] {subprocess.py:93} INFO -     - be included in your $PATH
[2025-08-06T03:33:11.662+0000] {subprocess.py:93} INFO -     - be set via $GIT_PYTHON_GIT_EXECUTABLE
[2025-08-06T03:33:11.662+0000] {subprocess.py:93} INFO -     - explicitly set via git.refresh(<full-path-to-git-executable>)
[2025-08-06T03:33:11.663+0000] {subprocess.py:93} INFO - 
[2025-08-06T03:33:11.664+0000] {subprocess.py:93} INFO - All git commands will error until this is rectified.
[2025-08-06T03:33:11.664+0000] {subprocess.py:93} INFO - 
[2025-08-06T03:33:11.665+0000] {subprocess.py:93} INFO - This initial message can be silenced or aggravated in the future by setting the
[2025-08-06T03:33:11.666+0000] {subprocess.py:93} INFO - $GIT_PYTHON_REFRESH environment variable. Use one of the following values:
[2025-08-06T03:33:11.666+0000] {subprocess.py:93} INFO -     - quiet|q|silence|s|silent|none|n|0: for no message or exception
[2025-08-06T03:33:11.667+0000] {subprocess.py:93} INFO -     - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
[2025-08-06T03:33:11.668+0000] {subprocess.py:93} INFO -     - error|e|exception|raise|r|2: for a raised exception
[2025-08-06T03:33:11.670+0000] {subprocess.py:93} INFO - 
[2025-08-06T03:33:11.671+0000] {subprocess.py:93} INFO - Example:
[2025-08-06T03:33:11.672+0000] {subprocess.py:93} INFO -     export GIT_PYTHON_REFRESH=quiet
[2025-08-06T03:33:11.673+0000] {subprocess.py:93} INFO - 
[2025-08-06T03:33:11.753+0000] {subprocess.py:93} INFO - 2025/08/06 03:33:11 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
[2025-08-06T03:33:19.462+0000] {subprocess.py:93} INFO - [31m2025/08/06 03:33:19 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.[0m
[2025-08-06T03:33:21.784+0000] {subprocess.py:93} INFO - Run ID: 22a36f0a39954f1981e471fde98c54dd
[2025-08-06T03:33:21.785+0000] {subprocess.py:93} INFO - üèÉ View run dashing-kit-228 at: http://mlflow:5000/#/experiments/1/runs/22a36f0a39954f1981e471fde98c54dd
[2025-08-06T03:33:21.787+0000] {subprocess.py:93} INFO - üß™ View experiment at: http://mlflow:5000/#/experiments/1
[2025-08-06T03:33:21.798+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-06T03:33:21.809+0000] {subprocess.py:93} INFO -   File "/opt/***/ml_pipeline/train/train_task.py", line 223, in <module>
[2025-08-06T03:33:21.816+0000] {subprocess.py:93} INFO -     main()
[2025-08-06T03:33:21.825+0000] {subprocess.py:93} INFO -   File "/opt/***/ml_pipeline/train/train_task.py", line 217, in main
[2025-08-06T03:33:21.827+0000] {subprocess.py:93} INFO -     register_model_with_mlflow(model, metrics)
[2025-08-06T03:33:21.829+0000] {subprocess.py:93} INFO -   File "/opt/***/ml_pipeline/train/train_task.py", line 141, in register_model_with_mlflow
[2025-08-06T03:33:21.830+0000] {subprocess.py:93} INFO -     mlflow.sklearn.log_model(model, artifact_path="model")
[2025-08-06T03:33:21.831+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/mlflow/sklearn/__init__.py", line 426, in log_model
[2025-08-06T03:33:21.833+0000] {subprocess.py:93} INFO -     return Model.log(
[2025-08-06T03:33:21.835+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^
[2025-08-06T03:33:21.836+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/mlflow/models/model.py", line 1298, in log
[2025-08-06T03:33:21.838+0000] {subprocess.py:93} INFO -     client.log_model_artifacts(model.model_id, local_path)
[2025-08-06T03:33:21.840+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/mlflow/tracking/client.py", line 5522, in log_model_artifacts
[2025-08-06T03:33:21.842+0000] {subprocess.py:93} INFO -     return self._tracking_client.log_model_artifacts(model_id, local_dir)
[2025-08-06T03:33:21.844+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-06T03:33:21.845+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/mlflow/tracking/_tracking_service/client.py", line 881, in log_model_artifacts
[2025-08-06T03:33:21.847+0000] {subprocess.py:93} INFO -     self._get_artifact_repo(model_id, resource="logged_model").log_artifacts(local_dir)
[2025-08-06T03:33:21.848+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/mlflow/store/artifact/s3_artifact_repo.py", line 286, in log_artifacts
[2025-08-06T03:33:21.849+0000] {subprocess.py:93} INFO -     self._upload_file(
[2025-08-06T03:33:21.850+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/mlflow/store/artifact/s3_artifact_repo.py", line 234, in _upload_file
[2025-08-06T03:33:21.852+0000] {subprocess.py:93} INFO -     s3_client.upload_file(Filename=local_file, Bucket=bucket, Key=key, ExtraArgs=extra_args)
[2025-08-06T03:33:21.853+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/boto3/s3/inject.py", line 145, in upload_file
[2025-08-06T03:33:21.857+0000] {subprocess.py:93} INFO -     return transfer.upload_file(
[2025-08-06T03:33:21.858+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2025-08-06T03:33:21.859+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/boto3/s3/transfer.py", line 371, in upload_file
[2025-08-06T03:33:21.861+0000] {subprocess.py:93} INFO -     future.result()
[2025-08-06T03:33:21.863+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/s3transfer/futures.py", line 103, in result
[2025-08-06T03:33:21.864+0000] {subprocess.py:93} INFO -     return self._coordinator.result()
[2025-08-06T03:33:21.867+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-06T03:33:21.868+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/s3transfer/futures.py", line 266, in result
[2025-08-06T03:33:21.870+0000] {subprocess.py:93} INFO -     raise self._exception
[2025-08-06T03:33:21.873+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/s3transfer/tasks.py", line 139, in __call__
[2025-08-06T03:33:21.874+0000] {subprocess.py:93} INFO -     return self._execute_main(kwargs)
[2025-08-06T03:33:21.875+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-06T03:33:21.876+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/s3transfer/tasks.py", line 162, in _execute_main
[2025-08-06T03:33:21.878+0000] {subprocess.py:93} INFO -     return_value = self._main(**kwargs)
[2025-08-06T03:33:21.879+0000] {subprocess.py:93} INFO -                    ^^^^^^^^^^^^^^^^^^^^
[2025-08-06T03:33:21.881+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/s3transfer/upload.py", line 764, in _main
[2025-08-06T03:33:21.882+0000] {subprocess.py:93} INFO -     client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
[2025-08-06T03:33:21.883+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/botocore/client.py", line 553, in _api_call
[2025-08-06T03:33:21.884+0000] {subprocess.py:93} INFO -     return self._make_api_call(operation_name, kwargs)
[2025-08-06T03:33:21.886+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-06T03:33:21.887+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/botocore/client.py", line 989, in _make_api_call
[2025-08-06T03:33:21.888+0000] {subprocess.py:93} INFO -     http, parsed_response = self._make_request(
[2025-08-06T03:33:21.890+0000] {subprocess.py:93} INFO -                             ^^^^^^^^^^^^^^^^^^^
[2025-08-06T03:33:21.891+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/botocore/client.py", line 1015, in _make_request
[2025-08-06T03:33:21.892+0000] {subprocess.py:93} INFO -     return self._endpoint.make_request(operation_model, request_dict)
[2025-08-06T03:33:21.894+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-06T03:33:21.895+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/botocore/endpoint.py", line 119, in make_request
[2025-08-06T03:33:21.896+0000] {subprocess.py:93} INFO -     return self._send_request(request_dict, operation_model)
[2025-08-06T03:33:21.897+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-06T03:33:21.898+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/botocore/endpoint.py", line 198, in _send_request
[2025-08-06T03:33:21.899+0000] {subprocess.py:93} INFO -     request = self.create_request(request_dict, operation_model)
[2025-08-06T03:33:21.901+0000] {subprocess.py:93} INFO -               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-06T03:33:21.902+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/botocore/endpoint.py", line 134, in create_request
[2025-08-06T03:33:21.903+0000] {subprocess.py:93} INFO -     self._event_emitter.emit(
[2025-08-06T03:33:21.904+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/botocore/hooks.py", line 412, in emit
[2025-08-06T03:33:21.906+0000] {subprocess.py:93} INFO -     return self._emitter.emit(aliased_event_name, **kwargs)
[2025-08-06T03:33:21.907+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-06T03:33:21.908+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/botocore/hooks.py", line 256, in emit
[2025-08-06T03:33:21.909+0000] {subprocess.py:93} INFO -     return self._emit(event_name, kwargs)
[2025-08-06T03:33:21.910+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-06T03:33:21.911+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/botocore/hooks.py", line 239, in _emit
[2025-08-06T03:33:21.912+0000] {subprocess.py:93} INFO -     response = handler(**kwargs)
[2025-08-06T03:33:21.913+0000] {subprocess.py:93} INFO -                ^^^^^^^^^^^^^^^^^
[2025-08-06T03:33:21.914+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/botocore/signers.py", line 105, in handler
[2025-08-06T03:33:21.915+0000] {subprocess.py:93} INFO -     return self.sign(operation_name, request)
[2025-08-06T03:33:21.916+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-06T03:33:21.917+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/botocore/signers.py", line 195, in sign
[2025-08-06T03:33:21.919+0000] {subprocess.py:93} INFO -     auth.add_auth(request)
[2025-08-06T03:33:21.920+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/botocore/auth.py", line 418, in add_auth
[2025-08-06T03:33:21.922+0000] {subprocess.py:93} INFO -     raise NoCredentialsError()
[2025-08-06T03:33:21.923+0000] {subprocess.py:93} INFO - botocore.exceptions.NoCredentialsError: Unable to locate credentials
[2025-08-06T03:33:22.471+0000] {subprocess.py:93} INFO - ERROR: failed to reproduce 'train': failed to run: python train/train_task.py, exited with 1
[2025-08-06T03:33:22.845+0000] {subprocess.py:97} INFO - Command exited with return code 255
[2025-08-06T03:33:22.847+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-06T03:33:22.863+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 255.
[2025-08-06T03:33:22.873+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ml_pipeline_dvc, task_id=train_dvc, run_id=manual__2025-08-06T03:27:26.716603+00:00, execution_date=20250806T032726, start_date=20250806T033300, end_date=20250806T033322
[2025-08-06T03:33:22.901+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 9 for task train_dvc (Bash command failed. The command returned a non-zero exit code 255.; 386)
[2025-08-06T03:33:22.952+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-06T03:33:22.977+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-06T03:33:22.980+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
