[2025-08-06T03:24:29.216+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-06T03:24:29.271+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_rollback.rollback_model manual__2025-08-06T03:24:22.982143+00:00 [queued]>
[2025-08-06T03:24:29.285+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_rollback.rollback_model manual__2025-08-06T03:24:22.982143+00:00 [queued]>
[2025-08-06T03:24:29.286+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-06T03:24:29.320+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): rollback_model> on 2025-08-06 03:24:22.982143+00:00
[2025-08-06T03:24:29.360+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=166) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-06T03:24:29.369+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'model_rollback', 'rollback_model', 'manual__2025-08-06T03:24:22.982143+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/model_rollback_dag.py', '--cfg-path', '/tmp/tmpdh7h43vg']
[2025-08-06T03:24:29.382+0000] {standard_task_runner.py:63} INFO - Started process 170 to run task
[2025-08-06T03:24:29.388+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask rollback_model
[2025-08-06T03:24:29.550+0000] {task_command.py:426} INFO - Running <TaskInstance: model_rollback.rollback_model manual__2025-08-06T03:24:22.982143+00:00 [running]> on host 1d9cc99197c4
[2025-08-06T03:24:29.758+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='model_rollback' AIRFLOW_CTX_TASK_ID='rollback_model' AIRFLOW_CTX_EXECUTION_DATE='2025-08-06T03:24:22.982143+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-06T03:24:22.982143+00:00'
[2025-08-06T03:24:29.762+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-06T03:24:29.852+0000] {warnings.py:110} WARNING - /opt/***/dags/model_rollback_dag.py:18: FutureWarning: ``mlflow.tracking.client.MlflowClient.get_latest_versions`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/latest/model-registry.html#migrating-from-stages
  versions = client.get_latest_versions("FraudDetectionModel")

[2025-08-06T03:24:30.028+0000] {logging_mixin.py:188} INFO - Rollback failed: Registered Model with name=FraudDetectionModel not found
[2025-08-06T03:24:30.036+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-06T03:24:30.037+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/model_rollback_dag.py", line 49, in rollback_model
    raise e
  File "/opt/airflow/dags/model_rollback_dag.py", line 18, in rollback_model
    versions = client.get_latest_versions("FraudDetectionModel")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mlflow/utils/annotations.py", line 188, in deprecated_func
    return obj(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mlflow/tracking/client.py", line 4026, in get_latest_versions
    self._raise_if_prompt(name)
  File "/home/airflow/.local/lib/python3.12/site-packages/mlflow/tracking/client.py", line 5334, in _raise_if_prompt
    rm = self.get_registered_model(name)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mlflow/tracking/client.py", line 3945, in get_registered_model
    rm = self._get_registry_client().get_registered_model(name)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mlflow/tracking/_model_registry/client.py", line 171, in get_registered_model
    return self.store.get_registered_model(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mlflow/store/model_registry/file_store.py", line 423, in get_registered_model
    raise MlflowException(
mlflow.exceptions.MlflowException: Registered Model with name=FraudDetectionModel not found
[2025-08-06T03:24:30.070+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=model_rollback, task_id=rollback_model, run_id=manual__2025-08-06T03:24:22.982143+00:00, execution_date=20250806T032422, start_date=20250806T032429, end_date=20250806T032430
[2025-08-06T03:24:30.101+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task rollback_model (Registered Model with name=FraudDetectionModel not found; 170)
[2025-08-06T03:24:30.151+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-06T03:24:30.242+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-06T03:24:30.247+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
