[2025-08-11T20:45:46.913+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-11T20:45:47.047+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline_dvc.preprocess_dvc manual__2025-08-11T20:45:44.553599+00:00 [queued]>
[2025-08-11T20:45:47.069+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline_dvc.preprocess_dvc manual__2025-08-11T20:45:44.553599+00:00 [queued]>
[2025-08-11T20:45:47.082+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-11T20:45:47.167+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): preprocess_dvc> on 2025-08-11 20:45:44.553599+00:00
[2025-08-11T20:45:47.184+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=412) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-11T20:45:47.195+0000] {standard_task_runner.py:63} INFO - Started process 413 to run task
[2025-08-11T20:45:47.189+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline_dvc', 'preprocess_dvc', 'manual__2025-08-11T20:45:44.553599+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/train_pipeline_dag.py', '--cfg-path', '/tmp/tmp0un0gyg_']
[2025-08-11T20:45:47.198+0000] {standard_task_runner.py:91} INFO - Job 74: Subtask preprocess_dvc
[2025-08-11T20:45:47.388+0000] {task_command.py:426} INFO - Running <TaskInstance: ml_pipeline_dvc.preprocess_dvc manual__2025-08-11T20:45:44.553599+00:00 [running]> on host 217f54bcc495
[2025-08-11T20:45:47.729+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='yas' AIRFLOW_CTX_DAG_ID='ml_pipeline_dvc' AIRFLOW_CTX_TASK_ID='preprocess_dvc' AIRFLOW_CTX_EXECUTION_DATE='2025-08-11T20:45:44.553599+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-11T20:45:44.553599+00:00'
[2025-08-11T20:45:47.731+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-11T20:45:47.764+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-11T20:45:47.766+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/ml_pipeline && dvc repro preprocess']
[2025-08-11T20:45:47.787+0000] {subprocess.py:86} INFO - Output:
[2025-08-11T20:45:53.895+0000] {subprocess.py:93} INFO - ERROR: failed to reproduce 'preprocess': The AWS Access Key Id you provided does not exist in our records.: An error occurred (InvalidAccessKeyId) when calling the ListObjectsV2 operation: The AWS Access Key Id you provided does not exist in our records.
[2025-08-11T20:45:54.413+0000] {subprocess.py:97} INFO - Command exited with return code 255
[2025-08-11T20:45:54.414+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-11T20:45:54.429+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 255.
[2025-08-11T20:45:54.437+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=ml_pipeline_dvc, task_id=preprocess_dvc, run_id=manual__2025-08-11T20:45:44.553599+00:00, execution_date=20250811T204544, start_date=20250811T204547, end_date=20250811T204554
[2025-08-11T20:45:54.464+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 74 for task preprocess_dvc (Bash command failed. The command returned a non-zero exit code 255.; 413)
[2025-08-11T20:45:54.498+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-11T20:45:54.531+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-11T20:45:54.533+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
