[2025-08-11T19:04:03.347+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-11T19:04:03.400+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline_dvc.preprocess_dvc manual__2025-08-11T18:58:53.767137+00:00 [queued]>
[2025-08-11T19:04:03.417+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline_dvc.preprocess_dvc manual__2025-08-11T18:58:53.767137+00:00 [queued]>
[2025-08-11T19:04:03.418+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-08-11T19:04:03.445+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): preprocess_dvc> on 2025-08-11 18:58:53.767137+00:00
[2025-08-11T19:04:03.453+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2771) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-11T19:04:03.456+0000] {standard_task_runner.py:63} INFO - Started process 2772 to run task
[2025-08-11T19:04:03.456+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline_dvc', 'preprocess_dvc', 'manual__2025-08-11T18:58:53.767137+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/train_pipeline_dag.py', '--cfg-path', '/tmp/tmpsijt_y6f']
[2025-08-11T19:04:03.458+0000] {standard_task_runner.py:91} INFO - Job 50: Subtask preprocess_dvc
[2025-08-11T19:04:03.550+0000] {task_command.py:426} INFO - Running <TaskInstance: ml_pipeline_dvc.preprocess_dvc manual__2025-08-11T18:58:53.767137+00:00 [running]> on host 631cb2647807
[2025-08-11T19:04:03.686+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='yas' AIRFLOW_CTX_DAG_ID='ml_pipeline_dvc' AIRFLOW_CTX_TASK_ID='preprocess_dvc' AIRFLOW_CTX_EXECUTION_DATE='2025-08-11T18:58:53.767137+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-11T18:58:53.767137+00:00'
[2025-08-11T19:04:03.687+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-11T19:04:03.708+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-11T19:04:03.710+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/ml_pipeline && dvc repro preprocess']
[2025-08-11T19:04:03.724+0000] {subprocess.py:86} INFO - Output:
[2025-08-11T19:04:09.015+0000] {subprocess.py:93} INFO - ERROR: failed to reproduce 'preprocess': The AWS Access Key Id you provided does not exist in our records.: An error occurred (InvalidAccessKeyId) when calling the ListObjectsV2 operation: The AWS Access Key Id you provided does not exist in our records.
[2025-08-11T19:04:09.585+0000] {subprocess.py:97} INFO - Command exited with return code 255
[2025-08-11T19:04:09.587+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-11T19:04:09.606+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 255.
[2025-08-11T19:04:09.615+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ml_pipeline_dvc, task_id=preprocess_dvc, run_id=manual__2025-08-11T18:58:53.767137+00:00, execution_date=20250811T185853, start_date=20250811T190403, end_date=20250811T190409
[2025-08-11T19:04:09.641+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 50 for task preprocess_dvc (Bash command failed. The command returned a non-zero exit code 255.; 2772)
[2025-08-11T19:04:09.683+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-11T19:04:09.725+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-11T19:04:09.730+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
